# Generated by Django 5.2.13 on 2026-04-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price_eur_mwh', models.FloatField()),
                ('volume_mw', models.FloatField()),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
    ]
